---
title: "Epiphytes__vs_Bathymetry"
author: "Simon"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(terra)
library(Utilities.Package)
library(magick)
library(sf)
```

```{r detect fisherman footprints}
library(imager)
image <- image_read("Data/RGB_Epiphytes.tif")

temp_image_path <- tempfile(fileext = ".png")
image_write(image, path = temp_image_path, format = "png")

image <- load.image(temp_image_path)

# Convert to grayscale
gray_image <- grayscale(image)

# Apply Gaussian blur to reduce noise
blurred_image <- isoblur(gray_image, 2)

```

```{r Epi Bathy}

if(!file.exists("Data/df_bathy.csv")){
  mask <- vect("Data/Epi_Laurent_02072024.shp")
  img_multi <- rast("Data/Epi_Laurent_02072024.tif") %>% 
    mask(mask)
  img_DEM <- rast("Data/DEM_Epiphytes.tif") 
  pred <- rast("Data/Epi_Laurent_02072024_DISCOV_InvaSea_pred.tif") %>% 
    mask(mask)
  
  img_DEM_rs <- terra::resample(img_DEM, img_multi)%>% 
    mask(mask)
  pred_rs <- terra::resample(pred, img_multi)%>% 
    mask(mask)
  
  ext(pred_rs) == ext(img_multi)
  ext(img_DEM_rs) == ext(img_multi)
  
  img <- rast(list(img_multi, img_DEM_rs, pred_rs))
  
  names(img) <- c(paste0("B",c(1:10)),"DEM","Pred")
  
  df <- img %>%
    as.data.frame(xy=T) %>% 
    dplyr::filter(B1 != 0,
                  Pred != 0,
                  !is.na(DEM))
  
  df_bathy <- df %>% 
    mutate(Bathy = round(DEM),
           pxl_ID = c(1:nrow(.))) %>% 
    pivot_longer(-c(pxl_ID,DEM,Pred,x,y,Bathy), names_to = "Band", values_to = "Ref") %>% 
    mutate(Wavelength = case_when(Band == "B1" ~ 444,
                                  Band == "B2" ~ 475,
                                  Band == "B3" ~ 531,
                                  Band == "B4" ~ 560,
                                  Band == "B5" ~ 650,
                                  Band == "B6" ~ 668,
                                  Band == "B7" ~ 705,
                                  Band == "B8" ~ 717,
                                  Band == "B9" ~ 740,
                                  Band == "B10" ~ 840))%>%
  dplyr::filter(Pred == 3) %>% 
  group_by(Bathy, Wavelength) %>%
  reframe(x = mean(x),
          y = mean(y),
          Ref = mean(Ref),
          Ref_abs = abs(Ref))
  
  
  write.csv(df_bathy,"Data/df_bathy.csv", row.names = F)
  
  rm(img_multi)
  rm(pred)
  rm(img_DEM_rs)
  rm(pred_rs)
  rm(img)
  rm(df)

}else{
  df_bathy <- read.csv("Data/df_bathy.csv")
}

df <- df_bathy 

ggplot(df, aes(x = Wavelength))+
  geom_line(aes(y = Ref))+
  geom_ribbon(aes(ymin = Ref - Ref_abs, ymax = Ref+Ref_abs), alpha = 0.3)+
  facet_wrap(~ Bathy)+
  theme_Bede()

```


```{r Slope Bathy}

mask <- vect("Data/Epi_Laurent_02072024.shp")
img_multi <- rast("Data/Epi_Laurent_02072024.tif") %>% 
  mask(mask)
img_DEM <- rast("Data/DEM_Epiphytes.tif") 
pred <- rast("Data/Epi_Laurent_02072024_DISCOV_InvaSea_pred.tif") %>% 
  mask(mask)

img_DEM_rs <- terra::resample(img_DEM, img_multi)%>% 
  mask(mask)
pred_rs <- terra::resample(pred, img_multi)%>% 
  mask(mask)

ext(pred_rs) == ext(img_multi)
ext(img_DEM_rs) == ext(img_multi)

img <- rast(list(img_multi, img_DEM_rs, pred_rs))

names(img) <- c(paste0("B",c(1:10)),"DEM","Pred")

df <- img %>%
  as.data.frame(xy=T) %>% 
  dplyr::select(DEM,B7,B9,Pred) %>% 
  dplyr::filter(B9 != 0,
                Pred ==3,
                !is.na(DEM)) %>% 
  mutate(NDIRI = (`B9`-`B7`)/(`B7`+`B9`))


plot <- df %>% 
  ggplot(aes(x = DEM, y = NDIRI))+
  geom_smooth(method = "gam", color = "black")+
  geom_point(alpha = 0.05)+
  ylab("IR Slope")+
  xlab("Heigh above the Geoid (m)")+
  theme_Bede()+
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12))
    
ggsave("Height_vs_Slope.png", width = 1200*4, height = 900*4, unit = "px" )
```



